//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Application.Context.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GF.Application.Context.Resource.ResourceMessage", typeof(ResourceMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帐号{0}已经被注册.
        /// </summary>
        internal static string ex_AccountExist {
            get {
                return ResourceManager.GetString("ex_AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帐号信息不存在.
        /// </summary>
        internal static string ex_AccountIsNotExist {
            get {
                return ResourceManager.GetString("ex_AccountIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱{0}已经被注册.
        /// </summary>
        internal static string ex_EmailExist {
            get {
                return ResourceManager.GetString("ex_EmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份证{0}已经被注册.
        /// </summary>
        internal static string ex_IdentityCardNumberExist {
            get {
                return ResourceManager.GetString("ex_IdentityCardNumberExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您今年已经填报过该志愿.
        /// </summary>
        internal static string ex_UniversityApplicationExist {
            get {
                return ResourceManager.GetString("ex_UniversityApplicationExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此招生计划已经存在.
        /// </summary>
        internal static string ex_UnversityEnrollPlanExist {
            get {
                return ResourceManager.GetString("ex_UnversityEnrollPlanExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}目前没有招生计划.
        /// </summary>
        internal static string ex_UnversityNoEnrollPlan {
            get {
                return ResourceManager.GetString("ex_UnversityNoEnrollPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 验证信息已发送到您邮箱，请您查收.
        /// </summary>
        internal static string info_ActiveMailSend {
            get {
                return ResourceManager.GetString("info_ActiveMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亲爱的用户 {0}  您好！&lt;/p&gt;感谢您注册GloriousFuture社区，您只需要点击下面链接，激活您的帐户，您便可以享受GloriousFuture各项服务。&lt;/br&gt;&lt;a href=&apos;http://www.google.com.hk&apos;&gt;google&lt;/a&gt;&lt;/br&gt;(如果无法点击该URL链接地址，请将它复制并粘帖到浏览器的地址输入框，然后单击回车即可。该链接使用后将立即失效。) &lt;/br&gt;(重新发送激活码：&lt;a href=&apos;http://www.google.com.hk&apos;&gt;google&lt;/a&gt; &lt;/br&gt;.
        /// </summary>
        internal static string info_EmailContentBodyActivationCode {
            get {
                return ResourceManager.GetString("info_EmailContentBodyActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亲爱的用户 {0} 您好！&lt;/p&gt;感谢您注册GloriousFuture社区，您已经成功修改了密码,请您使用新密码登录网站，您便可以享受GloriousFuture各项服务。&lt;/br&gt;&lt;a href=&apos;http://www.google.com.hk&apos;&gt;google&lt;/a&gt;&lt;/br&gt;(如果无法点击该URL链接地址，请将它复制并粘帖到浏览器的地址输入框，然后单击回车即可。该链接使用后将立即失效。) &lt;/br&gt;(重新发送激活码：&lt;a href=&apos;http://www.google.com.hk&apos;&gt;google&lt;/a&gt; &lt;/br&gt;.
        /// </summary>
        internal static string info_EmailContentBodyChangePassword {
            get {
                return ResourceManager.GetString("info_EmailContentBodyChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亲爱的用户 {0} 您好！&lt;/p&gt;感谢您注册GloriousFuture社区，您已经成功为帐号进行了账户充值。&lt;/br&gt;&lt;a href=&apos;http://www.google.com.hk&apos;&gt;google&lt;/a&gt;&lt;/br&gt;(如果无法点击该URL链接地址，请将它复制并粘帖到浏览器的地址输入框，然后单击回车即可。该链接使用后将立即失效。) &lt;/br&gt;(重新发送激活码：&lt;a href=&apos;http://www.google.com.hk&apos;&gt;google&lt;/a&gt; &lt;/br&gt;.
        /// </summary>
        internal static string info_EmailContentBodyRecharge {
            get {
                return ResourceManager.GetString("info_EmailContentBodyRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亲爱的用户 {0} 您好！&lt;/p&gt;感谢您注册GloriousFuture社区，您已经提交了重置密码申请，请您点击以下链接，完成密码重置，您便可以享受GloriousFuture各项服务。&lt;/br&gt;&lt;a href=&apos;http://www.google.com.hk&apos;&gt;google&lt;/a&gt;&lt;/br&gt;(如果无法点击该URL链接地址，请将它复制并粘帖到浏览器的地址输入框，然后单击回车即可。该链接使用后将立即失效。) &lt;/br&gt;(重新发送激活码：&lt;a href=&apos;http://www.google.com.hk&apos;&gt;google&lt;/a&gt; &lt;/br&gt;.
        /// </summary>
        internal static string info_EmailContentBodyResetPassword {
            get {
                return ResourceManager.GetString("info_EmailContentBodyResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GloriousFuture]密码重置通知.
        /// </summary>
        internal static string info_EmailSbujectResetPassword {
            get {
                return ResourceManager.GetString("info_EmailSbujectResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GloriousFuture]帐户激活通知.
        /// </summary>
        internal static string info_EmailSubjectActivationCode {
            get {
                return ResourceManager.GetString("info_EmailSubjectActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GloriousFuture]密码修改通知.
        /// </summary>
        internal static string info_EmailSubjectChangePassword {
            get {
                return ResourceManager.GetString("info_EmailSubjectChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GloriousFuture]账户充值通知.
        /// </summary>
        internal static string info_EmailSubjectRecharge {
            get {
                return ResourceManager.GetString("info_EmailSubjectRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码重置邮件已经发到您邮箱，请您查收.
        /// </summary>
        internal static string info_ResetPassword {
            get {
                return ResourceManager.GetString("info_ResetPassword", resourceCulture);
            }
        }
    }
}
