//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GF.Domain.Context.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GF.Domain.Context.Resource.ResourceValidation", typeof(ResourceValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户名字不能为空.
        /// </summary>
        internal static string Warning_Account_AccountName {
            get {
                return ResourceManager.GetString("Warning_Account_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮件不能为空.
        /// </summary>
        internal static string Warning_Account_Email {
            get {
                return ResourceManager.GetString("Warning_Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 性别不能为空.
        /// </summary>
        internal static string Warning_Account_Gender {
            get {
                return ResourceManager.GetString("Warning_Account_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份证号码不能为空.
        /// </summary>
        internal static string Warning_Account_IDCardNumber {
            get {
                return ResourceManager.GetString("Warning_Account_IDCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名不能为空.
        /// </summary>
        internal static string Warning_Account_Name {
            get {
                return ResourceManager.GetString("Warning_Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码只能是6到12位的字母和数字.
        /// </summary>
        internal static string Warning_Account_Password {
            get {
                return ResourceManager.GetString("Warning_Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 城市不能为空.
        /// </summary>
        internal static string Warning_Achievement_City {
            get {
                return ResourceManager.GetString("Warning_Achievement_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 省份不能为空.
        /// </summary>
        internal static string Warning_Achievement_Province {
            get {
                return ResourceManager.GetString("Warning_Achievement_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分数不能为空.
        /// </summary>
        internal static string Warning_Achievement_Score {
            get {
                return ResourceManager.GetString("Warning_Achievement_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 科目类别不能为空.
        /// </summary>
        internal static string Warning_Achievement_SpecialityType {
            get {
                return ResourceManager.GetString("Warning_Achievement_SpecialityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批次不能为空.
        /// </summary>
        internal static string Warning_Application_Batch {
            get {
                return ResourceManager.GetString("Warning_Application_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 志愿的序号不能为空.
        /// </summary>
        internal static string Warning_Application_Sequence {
            get {
                return ResourceManager.GetString("Warning_Application_Sequence", resourceCulture);
            }
        }
    }
}
